### ISSUE TITLE
Empty dark gray screen on startup

### ISSUE THREAD

**Issue by Kernald** [rogchap/wombat#54] opened 2021-03-29 22:41 UTC
Using 0.4.0 on Linux, I get an empty, dark gray (regular background colour) on startup, and nothing else. Starting from a terminal, I get this (and only this):

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
```

When closing the window, the process exits normally (0).

I didn't find any flag to make it more verbose or anything. It used to work on the same machine a few weeks ago, and can't figure out what might have changed since then. I tried removing `~/.cache/wombat` and `~/.local/share/Wombat`, it didn't make a difference.

What can I do to get more insights to troubleshoot this?

**Comment by kdevo** [comment] 2021-04-08 10:51
Having the same problem with `0.4.0` and `0.3.3` on Arch with Wayland.

Which Linux are you using? Do you use xorg or Wayland?

**Comment by Kernald** [comment] 2021-04-08 10:52
Archlinux as well, but Xorg (proprietary nVidia drivers).

**Comment by patkoscsaba** [comment] 2021-04-09 10:57
Same problem here since the beginning of April. Arch Linux, KDE, Xorg, nVidia proprietary drivers. Other programs I use doesn't seem to be affected.

**Comment by kdevo** [comment] 2021-04-09 11:20
Could this be related to the update of libwebkit2gtk ([webkit2gtk 2.32.0-1 pkg](https://archlinux.org/packages/extra/x86_64/webkit2gtk/)) which is used by this project?
See also [release notes](https://webkitgtk.org/security/WSA-2021-0003.html)

**Comment by Kernald** [comment] 2021-04-10 01:20
I'm not sure exactly how it's used, so I'm not sure if there's a dependency to upgrade or anything (I'm really not familiar with Go, but I couldn't find any direct reference to webkitgtk), but just rebuilding Wombat doesn't help.

**Comment by aschey** [comment] 2021-04-11 01:39
I believe this is caused by this Wails issue: https://github.com/wailsapp/wails/issues/658 (a recent webkit2gtk update broke it, as speculated). I just opened a PR to update Wails which should fix this.

**Comment by leaanthony** [comment] 2021-04-11 03:09
Thanks for opening this @aschey. It looks like recent version of gtkwebkit don't expose `window.external` any more so we have a patch against that now.

**Comment by patkoscsaba** [comment] 2021-04-15 13:04
Hey everyone. Can we have some kind of progress info on this one? Wombat is totally broken now, and alternatives are not that good.

**Comment by aschey** [comment] 2021-04-15 16:18
Currently waiting on my PR to be reviewed and merged. In the meantime, you can build from my branch here: https://github.com/aschey/wombat/tree/update-wails-and-go

**Comment by yswtrue** [comment] 2021-04-16 09:42
same problem here

**Closed** 2021-04-18 12:34 UTC

**Comment by patkoscsaba** [comment] 2021-04-23 15:34
Any chance of a release soon? I am stock with gRPC-UI tool for now and eagerly waiting a release of Wombat with this issues fixed.

**Comment by aschey** [comment] 2021-04-24 00:34
@patkoscsaba I'm not sure when the next version will be released so here's a build from the latest master branch that I did on my local machine: https://filebin.net/tqjpph3h7ef580zf

**Comment by rogchap** [comment] 2021-04-24 05:59
Sorry for the delay everyone. Just fixing up a few bugs and will get a new release cut soon. 🙏

**Comment by patkoscsaba** [comment] 2021-04-24 08:35
@aschey Thanks. That starts up and seems to be working. Even if there are a few bugs, it's better than not having anything.
@rogchap Sure, I am not complaining or pressuring you. After all it is a free and open source project. Take your time. And good job with Wombat. It is by far the best gRPC GUI client out there. I tried all the others while Wombat was not working, and I was disappointed. gRPC UI is decent, and it is cool that you can deploy it along with your server, but without realtime streams it is awkward to be used.
